### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by jchand99** [giawa/opengl4csharp#13]
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at OpenGL.Gl.DeleteTextures(Int32 n, UInt32[] textures)
   at OpenGL.Texture.Dispose(Boolean disposing)
   at OpenGL.Texture.Finalize()

That is the error message recieved.

**Comment by giawa** [comment]
Hey there,

Did you end up resolving this issue?  For posterity, do you mind including your solution in this issue?

Thanks!

**Comment by hellbender3069** [comment]
Hello Giawa, 
I seem to have run into the same problem using Visual Studio 2019 and the example code in a console application. It happens when the application is closed and i am not sure but when I try to step into the Delegates.glDeleteVertexArray(n, arrays) function I get the System.AccessViolationException. Since Delegates is a class of internal delegates I have no idea where they are pointing to. Since jchand99 has not published any solution I am a bit in the dark here about what is happening. 

Could you please be of any assistance?

With regards,
Michel

[Program.txt](https://github.com/giawa/opengl4csharp/files/4939871/Program.txt)

P.S. it seems to start acting up when I add the line for the new ShaderProgram. If I don't attach those and not paint the cube nothing is wrong. If I add the line for the ShaderProgram it gives this exception. I don't need to draw the cube to trigger it.

**Comment by jchand99** [comment]
Oof. I apologize for not responding for 3 years. I don't think I ended up figuring out what the issue was when I was using this. If I end up getting some time to look at it again soon I'll respond to this thread with what I find. Again, my apologies.
