### ISSUE TITLE
Glut Window Dimensions is not scaled to Vector2 or Vector3

### ISSUE THREAD

**Issue by RinzuTheCoder** [giawa/opengl4csharp#33]
The top right corner of a window with width 1200 and height of 720 has a vector2 coordinate at about (36, 21). is this correct? If Vector2.Zero is the center of the window shouldnt the top right corner be Vector2(600, 360)? If the origin of the Window was at the the bottom left corner wouldn't the top right corner be Vector2(1200, 720)?

**Comment by giawa** [comment]
I'm curious which program you are running to get these results.  It sounds like you are using Glut, which I don't think accounts for the program title bar in Windows.  That may be why you are getting an offset.  Those numbers come from Glut directly I believe.

If you use OpenGL.Platform (which uses SDL2) then you should get a range from 0,0 to 1200,720, since SDL2 does account for the title bar of the window.  Hopefully this explains it.

**Comment by giawa** [comment]
Do you have any update on this?  Will mark as closed if not.  Thanks

**Comment by RinzuTheCoder** [comment]
No do not,  has anyone else check it out? Im trying to make a game engine
and with recent events in my life i cant show you the back end. My
architecture is unique. This is all i feel comfortable showing

**Comment by giawa** [comment]
Are you using Glut?  Or are you using OpenGL.Platform (which uses SDL).  Since you used 'Glut' in the title I am guessing you are using someone else's library/code for window handling, in which case I think this issue belongs with that project.  If you can confirm that then I can close this.  Thanks

**Comment by RinzuTheCoder** [comment]
In this case i am the person who made the library

**Comment by RinzuTheCoder** [comment]
Im using glut

**Comment by giawa** [comment]
In that case I think it will be up to you (or Glut) to deal with scaling the co-ordinates to whatever co-ordinate system you would like.

**Comment by RinzuTheCoder** [comment]
How do i get in contact with devs of glut?

**Comment by giawa** [comment]
Hopefully you're using FreeGlut, as the original Glut is no longer in development.  You can find them here!  http://freeglut.sourceforge.net/  Good luck!
