### ISSUE TITLE
FileLoadException when starting program

### ISSUE THREAD

**Issue by SamusAranX** [giawa/opengl4csharp#37]
I'm using a .NET Core 3.1 console application as a base for a small OpenGL playground.
When setting it up, I just followed the steps outlined in the readme:

1. Install `Giawa.OpenGL` and  `Giawa.OpenGL.Platform`
2. Insert the example cube code:
```cs
using System;
using System.Numerics;
using OpenGL;

namespace Shady
{
	internal class Program
	{
		private const int WIDTH = 800;
		private const int HEIGHT = 480;

		private static VAO cube;

		private static void Main(string[] args)
		{
			// create an OpenGL window
			OpenGL.Platform.Window.CreateWindow("Shady", WIDTH, HEIGHT);

			var vertexShader = Resources.LoadTextResource("Shady.shaders.example.vsh");
			var fragShader = Resources.LoadTextResource("Shady.shaders.example.fsh");

			var shaderProgram = new ShaderProgram(vertexShader, fragShader);

			cube = Geometry.CreateCube(shaderProgram, new Vector3(-1, -1, -1), new Vector3(1, 1, 1));

			// handle events and render the frame
			while (OpenGL.Platform.Window.Open)
			{
				OpenGL.Platform.Window.HandleEvents();
				OnRenderFrame();
			}
		}

		private static void OnRenderFrame()
		{
			Gl.Viewport(0, 0, WIDTH, HEIGHT);
			Gl.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);

			cube.Program.Use();
			cube.Draw();

			OpenGL.Platform.Window.SwapBuffers();
		}
	}
}
```
Every time I run the app, it crashes on the CreateWindow line with this message:

> System.IO.FileLoadException: 'Could not load file or assembly 'OpenGL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)'

I have no idea what Visual Studio is trying to tell me. I assumed using nuget would spare me obtuse error messages like this

**Comment by giawa** [comment]
I wonder if this has something to do with installing both OpenGL.Platform and OpenGL.  OpenGL.Platform already contains OpenGL.  I wonder if the two are in conflict somehow when you have both installed.  Also, when using OpenGL.Platform you will need to add SDL2.dll to your executable path, as it is not included in the nuget package.  You can find the latest binaries of SDL here, and you'll need to ensure you pick the dll with the correct architecture (otherwise you will get a "BadImageFormatException").  Hopefully this helps!  It might be worth checking out the samples here, which should include all the dependencies to get up and running:  https://github.com/giawa/opengl4tutorials

**Comment by SamusAranX** [comment]
>  I wonder if the two are in conflict somehow when you have both installed.

That was exactly it, removing OpenGL made the program work. Thanks for your help!

**Comment by giawa** [comment]
Awesome, glad that worked!
