### ISSUE TITLE
Can't find anywhere else to ask this

### ISSUE THREAD

**Issue by ghost** [giawa/opengl4csharp#61]
Is there anywhere where the source for your game engine is available?

**Comment by giawa** [comment]
Are you talking about the voxel engine?  Or something different?  I've never gotten around to releasing the source code for the voxel engine - I don't think it would be useful as it is currently, since it was designed for a specific goal.  I might look into generalizing it in the future and releasing it.

**Comment by ghost** [comment]
> Are you talking about the voxel engine? Or something different? I've never gotten around to releasing the source code for the voxel engine - I don't think it would be useful as it is currently, since it was designed for a specific goal. I might look into generalizing it in the future and releasing it.

Yeah, I was talking about the voxel engine. I was curious because of the stuff on your website. I had not heard about it in awhile, and you describe it as "largely open-source".

**Comment by giawa** [comment]
Gotcha, ya the largely open source has to do with the math/opengl bindings/etc offered in this repo.  I might look at making the voxel portion open source at some point, but don't currently have plans to do so.
