### ISSUE TITLE
Issues about OpenGL.dll file

### ISSUE THREAD

**Issue by tony-yun** [giawa/opengl4csharp#65]
hello sir,

I'm learning on Youtube C# OpenGL Tutorial 1 : Opening a Window.
At 4:16, you mentioned that release and solution build , there will be new file named
OpenGL.dll config file and application extends. 
But I didnt got config file , i got application file (430KB), json file(5KB), pdb file(90KB), xml file(996KB). those 4files.
How can I get the config file, is there any problem since i using the visual studio 2022?

**Comment by giawa** [comment]
Hi there,

Thanks for trying out the project!  You can find that config file here in the git repo:  https://github.com/giawa/opengl4csharp/blob/dotnetcore/OpenGL/OpenGL.dll.config

Normally it should get copied to the output, but perhaps Visual Studio 2022 behaves differently (or there is an error in the project).  This config file is only necessary if you're using Linux, as it contains the mapping from .dll to .so that mono needs to bind to the correct OpenGL library.  Hopefully this helps!
